### ISSUE TITLE
[Bug]: Issues in non-Windows platforms

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Here's a checklist:
- [x] Incorrect detection of MSI values
<details>

<summary>Details (original comment)</summary>

Inside WSL:
![image](https://user-images.githubusercontent.com/56180050/220587578-89cecd2a-afe7-46cc-bb52-f6dda00ebae9.png)

The product code is incorrect, and the `InstallerType` is also replaced from `wix` to `msi`. Here is the correct entry, as shown in Windows. It even has some additional entries:
![image](https://user-images.githubusercontent.com/56180050/220586136-350c3366-9b90-45ca-b200-bda61adffcab.png)

</details>

- [ ] Komac does not remember/save the entered token

**Comment by russellbanks** [comment]
This is because the Msi.dll that Komac invokes is Windows-only, and I don't really know a way to be able to read an MSI database in Linux or macOS. Komac should still work on Linux (I haven't tested Komac on Linux), but MSI detection won't be as good/present..

**Comment by russellbanks** [comment]
For the token, Komac uses Windows Credentials which is the ideal way to store a token on Windows. Komac doesn't have any implementation to store the token securely on other operating systems. There are other ways to do it on other operating systems, and I have looked into libraries to achieve this ([secret-service](https://github.com/swiesend/secret-service), [kdewallet](https://github.com/purejava/kdewallet)), but it hasn't been a priority to implement it at the moment. I would like to do so at some point.

**Comment by russellbanks** [comment]
These are the only two things that are present in Komac on Windows but not other operating systems. Everything else works fully.

**Comment by sitiom** [comment]
> This is because the Msi.dll that Komac invokes is Windows-only, and I don't really know a way to be able to read an MSI database in Linux or macOS.

You might be interested with [msitools](https://wiki.gnome.org/msitools) and it's library `libmsi`:
![image](https://user-images.githubusercontent.com/56180050/220804016-a2950ae5-b3b7-4515-a0d2-be723ef2559e.png)

**Comment by russellbanks** [comment]
Thanks for sharing :) I've come acros msitools before but I haven't looked into it's underlying libmsi. I'll see how I can integrate this in Komac, whether through JNI, JNA, etc

**Comment by russellbanks** [comment]
Do you know how a Linux user gets libmsi? I've only found the code for it from within msitools

**Comment by sitiom** [comment]
> Do you know how a Linux user gets libmsi? I've only found the code for it from within msitools

I think it's bundled with the `msitools` package.

**Comment by vedantmgoyal2009** [comment]
`sudo apt install msitools`

**Comment by vedantmgoyal2009** [comment]
Option 1 is what I would go for. Just display some message to inform the users that Komac will install the package. For CI platforms, you could just install without any user confirmation. That way, I could then take Komac's advantage of being able to run cross-platform into my action as well.

**Comment by russellbanks** [comment]
I don't imagine msitools in available on mac though, so this could only open it up to Linux @vedantmgoyal2009

**Comment by vedantmgoyal2009** [comment]
Yes, but since most CIs use Windows and Linux, I have a little more confidence when removing the condition from the action (https://github.com/vedantmgoyal2009/winget-releaser/issues/126#issuecomment-1477260034). macOS support can be looked into later since it's not that widely used.

**Comment by sitiom** [comment]
> I don't imagine msitools in available on mac though

https://formulae.brew.sh/formula/msitools

**Comment by russellbanks** [comment]
Good news :) I'm working on getting data from the msi by analysing the binary data of the msi, similar to how inno and nullsoft detection etc works. This will work regardless of platform.

**Comment by russellbanks** [comment]
I've added MSI support for other platforms that aren't Windows in #151. It's not perfect, it's a little slower, and it would still be "cleaner" to use msi.dll, but the feature is there for non-Windows platforms.

**Comment by sitiom** [comment]
> I've added MSI support for other platforms that aren't Windows in #151. It's not perfect, it's a little slower, and it would still be "cleaner" to use msi.dll, but the feature is there for non-Windows platforms.

Tried it out, and it seems like it's dependent on `libmsi`? Seems like Komac isn't bundling that dependency:

```
libmsi.so: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libmsi.so) not found in resource path (/home/rycaeli/.jbang/cache/urls/15e3aa209b93e16fc9ca0afbec053c705ef3b76b41c016e9d5c6de3e4413dd68/Komac-1.6.0-all.jar)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:323)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483)
        at com.sun.jna.Library$Handler.<init>(Library.java:197)
        at com.sun.jna.Native.load(Native.java:622)
        at detection.files.msi.MsiLibrary$Companion.<clinit>(MsiLibrary.kt:38)
        at detection.files.msi.MsiLibrary.<clinit>(MsiLibrary.kt)
        at detection.files.msi.Msi.<init>(Msi.kt:29)
        at utils.FileAnalyser.<init>(FileAnalyser.kt:20)
        at commands.QuickUpdate.loopParameterUrls(QuickUpdate.kt:180)
        at commands.QuickUpdate.access$loopParameterUrls(QuickUpdate.kt:55)
        at commands.QuickUpdate$loopParameterUrls$1.invokeSuspend(QuickUpdate.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at commands.QuickUpdate.run(QuickUpdate.kt:75)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:290)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:303)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:441)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:438)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:458)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:465)
        at MainKt.main(Main.kt:17)
        Suppressed: java.lang.UnsatisfiedLinkError: libmsi.so: cannot open shared object file: No such file or directory
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:211)
                ... 27 more
        Suppressed: java.lang.UnsatisfiedLinkError: libmsi.so: cannot open shared object file: No such file or directory
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:224)
                ... 27 more
        Suppressed: java.io.IOException: Native library (linux-x86-64/libmsi.so) not found in resource path (/home/rycaeli/.jbang/cache/urls/15e3aa209b93e16fc9ca0afbec053c705ef3b76b41c016e9d5c6de3e4413dd68/Komac-1.6.0-all.jar)
```

**Comment by russellbanks** [comment]
> Tried it out, and it seems like it's dependent on `libmsi`? Seems like Komac isn't bundling that dependency:

Komac doesn't use libmsi or anything to do with libmsi anywhere. The only thing I can think of is that when it looks for an "msi" library, it looks for that on Linux. If that's the case I just have to change it to return a null instance of the msi library class when it's not Windows

**Comment by russellbanks** [comment]
I've updated it so the instance is only retrieved on Windows. That should resolve JNA looking for an MSI library on Linux.

**Comment by sitiom** [comment]
> The only thing I can think of is that when it looks for an "msi" library, it looks for that on Linux.

So it was finding for libmsi but wasn't using it?


> I've updated it so the instance is only retrieved on Windows. That should resolve JNA looking for an MSI library on Linux.
> 
> If you're able to, it would be great if you could try it with the [Nightly JAR](https://github.com/russellbanks/Komac/releases/tag/nightly)!

Works now, thanks!

**Comment by russellbanks** [comment]
> So it was finding for libmsi but wasn't using it?

Yeah the fallback implementation I made doesn't use any native depdenency (msi.dll, libmsi, etc)

**Comment by russellbanks** [comment]
@sitiom & @vedantmgoyal2009 , The next version of Komac will use libmsi. Although this means Komac has a dependency when using Linux, the values it gets will be on par with Windows in terms of accuracy. This is also signficantly more efficient than the previous implementation.

**Comment by sitiom** [comment]
> @sitiom & @vedantmgoyal2009 , The next version of Komac will use libmsi. Although this means Komac has a dependency when using Linux, the values it gets will be on par with Windows in terms of accuracy. This is also signficantly more efficient than the previous implementation.

Does that mean Winget Releaser should be updated to require libmsi?

**Comment by vedantmgoyal2009** [comment]
@russellbanks `libmsi` is also available on macOS.

https://github.com/russellbanks/Komac/issues/110#issuecomment-1478737408

Cam you test it on macOS as well and add macOS to the condition as well

https://github.com/russellbanks/Komac/blob/b32865d22a01e433734cebd4c481c0f25e63a7a6/src/main/kotlin/utils/msi/Msi.kt#L39-#46

**Comment by sitiom** [comment]
> @sitiom If you are updating all workflows to use Linux runner, according to https://github.com/russellbanks/Komac/issues/110#issuecomment-1483946680, I would advise not to change if that repository has an MSI installer. It might generate incorrect manifests in some cases. Windows would be still the preferred choice.

@vedantmgoyal2009 I've tested Winget Releaser with the latest version of Komac, and MSI manifests seem to generate correctly now.

**Comment by Okeanos** [comment]
Ran into this issue on macOS earlier with the following stacktrace:

```txt
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'libmsi':
dlopen(liblibmsi.dylib, 0x0009): tried: '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/./liblibmsi.dylib' (no such file), '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/../lib/liblibmsi.dylib' (no such file), 'liblibmsi.dylib' (no such file), '/usr/lib/liblibmsi.dylib' (no such file), '/Users/ng/liblibmsi.dylib' (no such file)
dlopen(liblibmsi.dylib, 0x0009): tried: '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/./liblibmsi.dylib' (no such file), '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/../lib/liblibmsi.dylib' (no such file), 'liblibmsi.dylib' (no such file), '/usr/lib/liblibmsi.dylib' (no such file), '/Users/ng/liblibmsi.dylib' (no such file)
dlopen(/Users/ng/Library/Frameworks/libmsi.framework/libmsi, 0x0009): tried: '/Users/ng/Library/Frameworks/libmsi.framework/libmsi' (no such file), '/System/Library/Frameworks/libmsi.framework/libmsi' (no such file)
dlopen(/Library/Frameworks/libmsi.framework/libmsi, 0x0009): tried: '/Library/Frameworks/libmsi.framework/libmsi' (no such file), '/System/Library/Frameworks/libmsi.framework/libmsi' (no such file)
dlopen(/System/Library/Frameworks/libmsi.framework/libmsi, 0x0009): tried: '/System/Library/Frameworks/libmsi.framework/libmsi' (no such file)
Native library (darwin-x86-64/liblibmsi.dylib) not found in resource path (/Users/ng/Downloads/Komac-1.11.0-all.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:323)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483)
	at com.sun.jna.Library$Handler.<init>(Library.java:197)
	at com.sun.jna.Native.load(Native.java:622)
	at utils.jna.LibMsi$Companion.<clinit>(LibMsi.kt:27)
	at utils.jna.LibMsi.<clinit>(LibMsi.kt)
	at utils.msi.Msi.getValuesLibMsi(Msi.kt:38)
	at utils.msi.Msi.<init>(Msi.kt:34)
	at utils.FileAnalyser.<init>(FileAnalyser.kt:37)
	at utils.FileAnalyser.<init>(FileAnalyser.kt:22)
	at network.Downloader.download(Downloader.kt:45)
	at network.Downloader$download$1.invokeSuspend(Downloader.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at commands.NewManifest.run(NewManifest.kt:101)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:306)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:458)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
	at MainKt.main(Main.kt:24)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(liblibmsi.dylib, 0x0009): tried: '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/./liblibmsi.dylib' (no such file), '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/../lib/liblibmsi.dylib' (no such file), 'liblibmsi.dylib' (no such file), '/usr/lib/liblibmsi.dylib' (no such file), '/Users/ng/liblibmsi.dylib' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:211)
		... 28 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(liblibmsi.dylib, 0x0009): tried: '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/./liblibmsi.dylib' (no such file), '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/../lib/liblibmsi.dylib' (no such file), 'liblibmsi.dylib' (no such file), '/usr/lib/liblibmsi.dylib' (no such file), '/Users/ng/liblibmsi.dylib' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:224)
		... 28 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/ng/Library/Frameworks/libmsi.framework/libmsi, 0x0009): tried: '/Users/ng/Library/Frameworks/libmsi.framework/libmsi' (no such file), '/System/Library/Frameworks/libmsi.framework/libmsi' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:268)
		... 28 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/libmsi.framework/libmsi, 0x0009): tried: '/Library/Frameworks/libmsi.framework/libmsi' (no such file), '/System/Library/Frameworks/libmsi.framework/libmsi' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:268)
		... 28 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/libmsi.framework/libmsi, 0x0009): tried: '/System/Library/Frameworks/libmsi.framework/libmsi' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:268)
		... 28 more
	Suppressed: java.io.IOException: Native library (darwin-x86-64/liblibmsi.dylib) not found in resource path (/Users/ng/Downloads/Komac-1.11.0-all.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1145)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:295)
		... 28 more
```

Note that JNA is attempting to locate `liblibmsi.dylib` and not `libmsi` as expected; don't yet know why and where the additional `lib`-prefix comes from. The initial prefix is part of `LibMsi.kt` where the name is declared as `libmsi`.

When using [msitools](https://formulae.brew.sh/formula/msitools) as provided by homebrew there's a few extra caveats:

- `libmsi` is installed into `/usr/local/lib` on Intel Macs (I assume it's `/opt/homebrew/lib` on Apple Silicon/ARM but that's a guess)
- `libmsi` is installed with the following naming schema:
  `libmsi-1.0.0.dylib -> ../Cellar/msitools/0.103/lib/libmsi-1.0.0.dylib`
  `libmsi-1.0.dylib -> ../Cellar/msitools/0.103/lib/libmsi-1.0.dylib`


As a result when using the jar file the invocation has to be `java -Djna.library.path=/usr/local/lib -jar build/libs/Komac-1.11.0-all.jar new` and `LibMsi.kt` updated to support `private const val LIBMSI = "msi-1.0"` in addition to the original `private const val LIBMSI = "libmsi"` in case of macOS as platform.

A quick test doesn't look to promising when trying to bake in the `jna.library.path` into the `tasks.jpackage`-task in the `build.gradle.kts` file specifically for macOS. It's probably better to have this user defined (along with the correct lib name) anyway. Thoughts?

**Comment by russellbanks** [comment]
This is fully resolved in the Rust rewrite :)

Komac 2.0.0 uses [keyring](https://crates.io/crates/keyring) to implement secure token storage and the [msi](https://crates.io/crates/msi) crate to implement the MSI functionality for every platform. Komac 2.0.0 has no runtime dependencies either.
