### ISSUE TITLE
[Bug]: Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property bestMatch has not been initialized

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```console
> Komac update --id ViGEm.ViGEmBus --version 1.22.0 --urls https://github.com/nefarius/ViGEmBus/releases/download/v1.22.0/ViGEmBus_1.22.0_x64_x86_arm64.exe
Latest version of ViGEm.ViGEmBus: 1.21.442
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property bestMatch has not been initialized
        at utils.UrlsToInstallerMatcher.matchInstallers(UrlsToInstallerMatcher.kt:54)
        at commands.QuickUpdate.loopParameterUrls(QuickUpdate.kt:265)
        at commands.QuickUpdate.access$loopParameterUrls(QuickUpdate.kt:49)
        at commands.QuickUpdate$loopParameterUrls$1.invokeSuspend(QuickUpdate.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at commands.QuickUpdate.run(QuickUpdate.kt:105)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:306)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:458)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
        at MainKt.main(Main.kt:24)
Failed to launch JVM
```

**Comment by russellbanks** [comment]
This is from the matching of previous installers to new installers. This shouldn't happen which is why it's lateinit in the first place. I'll keep this in mind and do some testing for that with the Rust rewrite.

As a note, you don't need to specify the same URL multiple times. Komac will pair each previous installer with a URL from the ones provided. Because of this, it internally gets put into a set so all duplicates are removed anyway.

**Comment by sitiom** [comment]
> As a note, you don't need to specify the same URL multiple times. Komac will pair each previous installer with a URL from the ones provided. Because of this, it internally gets put into a set so all duplicates are removed anyway.

Ah, right, fixed it. The error remains the same, though.
