### ISSUE TITLE
[Bug]: Failed to delete downloaded temp file

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```console
> Komac new
[Required] Enter the package identifier
Example: Microsoft.Excel
Package Identifier: Gyan.FFmpeg.Essentials

[Required] Enter the package version
Example: 7.49.1
Package Version: 6.1

[Required] Enter the Download URL to the installer
Installer URL: https://github.com/GyanD/codexffmpeg/releases/download/6.1/ffmpeg-6.1-essentials_build.zip

[Required] Select files to use
[x] /ffmpeg-6.1-essentials_build/bin/ffmpeg.exe
[x] /ffmpeg-6.1-essentials_build/bin/ffplay.exe
[x] /ffmpeg-6.1-essentials_build/bin/ffprobe.exe
[Confirm]
[Required] Select the nested installer type
[ ] EXE
[x] PORTABLE
[Optional] Enter the command line alias to be used for calling the package
Installer: ffmpeg.exe
Portable Command Alias:

[Optional] Enter the command line alias to be used for calling the package
Installer: ffplay.exe
Portable Command Alias:

[Optional] Enter the command line alias to be used for calling the package
Installer: ffprobe.exe
Portable Command Alias:

Exception in thread "main" java.io.IOException: failed to delete C:\Users\rycae\AppData\Local\Temp\Gyan.FFmpeg.Essentials 6.1 - 2023.12.15-15.46.13.zip
        at okio.JvmSystemFileSystem.delete(JvmSystemFileSystem.kt:137)
        at okio.FileSystem.delete(FileSystem.kt:115)
        at network.Downloader.download(Downloader.kt:67)
        at network.Downloader$download$1.invokeSuspend(Downloader.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at commands.NewManifest.run(NewManifest.kt:101)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:306)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:458)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
        at MainKt.main(Main.kt:24)
Exception in thread "Thread-10" java.io.IOException: failed to delete C:\Users\rycae\AppData\Local\Temp\Gyan.FFmpeg.Essentials 6.1 - 2023.12.15-15.46.13.zip
        at okio.JvmSystemFileSystem.delete(JvmSystemFileSystem.kt:137)
        at okio.FileSystem.delete(FileSystem.kt:115)
        at network.Downloader.downloadFile$lambda$4$lambda$3(Downloader.kt:89)
        at java.base/java.lang.Thread.run(Unknown Source)
Failed to launch JVM
```

Posting an issue here for reference, but I guess this won't be relevant on the rust rewrite.

**Comment by russellbanks** [comment]
This is probably due to an open file handle. In Rust, file handles are automatically closed as they're dropped. I also use [async-tempfile](https://crates.io/crates/async-tempfile) so that the file itself is deleted straight after its file handle is closed.
