### ISSUE TITLE
[Bug]: Failed to delete temp file

### ISSUE THREAD

**Issue by tictot** [russellbanks/Komac#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Appears to be a regression of #353.
Version: 1.11.0

```
PS C:\Users\User> komac new
[Required] Enter the package identifier
Example: Microsoft.Excel
Package Identifier: ColinPitrat.Caprice32

[Required] Enter the package version
Example: 2.37.3
Package Version: 1074f59

[Required] Enter the Download URL to the installer
Installer URL: https://github.com/ColinPitrat/caprice32/releases/download/latest/cap32-win64.zip

[Required] Select the nested installer type
[ ] EXE
[x] PORTABLE
[Optional] Enter the command line alias to be used for calling the package
Installer: /release/cap32-win64/cap32.exe
Portable Command Alias: cap32

Exception in thread "main" java.io.IOException: failed to delete C:\Users\User\AppData\Local\Temp\ColinPitrat.Caprice32 1074f59 - 2024.1.14-17.49.11.zip
        at okio.JvmSystemFileSystem.delete(JvmSystemFileSystem.kt:137)
        at okio.FileSystem.delete(FileSystem.kt:115)
        at network.Downloader.download(Downloader.kt:67)
        at network.Downloader$download$1.invokeSuspend(Downloader.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at commands.NewManifest.run(NewManifest.kt:101)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:306)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:458)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
        at MainKt.main(Main.kt:24)
Exception in thread "Thread-12" java.io.IOException: failed to delete C:\Users\User\AppData\Local\Temp\ColinPitrat.Caprice32 1074f59 - 2024.1.14-17.49.11.zip
        at okio.JvmSystemFileSystem.delete(JvmSystemFileSystem.kt:137)
        at okio.FileSystem.delete(FileSystem.kt:115)
        at network.Downloader.downloadFile$lambda$4$lambda$3(Downloader.kt:89)
        at java.base/java.lang.Thread.run(Unknown Source)
Failed to launch JVM
```

**Comment by russellbanks** [comment]
The library patch for #258 and #353 hadn't had a release published for it. Since then, Komac has been rewritten in Rust (version >2) and the issue isn't present there as tempfiles are handled by the operating system rather than Komac.

I hope for a release soon but I want to make sure that I'm not missing any functionality from Komac v1.
